crudexample/urls.py
from django.contrib import admin  
from django.urls import path  
from vehicle import views
urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('emp', views.emp),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]  

vehicle/models.py
from django.db import models
class Vehicle(models.Model):
    eid = models.CharField(max_length=20)
    etypeVehicle = models.CharField(max_length=100)
    emodel = models.CharField(max_length=100)
    ebrand = models.CharField(max_length=100)
    eplate = models.CharField(max_length=100)
    emileage = models.CharField(max_length=100)
    class Meta:
        db_table = "vehicle"

vehicle/forms.py
from django import forms
from vehicle.models import Vehicle


class VehicleForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = "__all__"

vehicle/views.py
from django.shortcuts import render, redirect
from vehicle.forms import VehicleForm
from vehicle.models import Vehicle
# Create your views here.
def emp(request):
    if request.method == "POST":
        form = VehicleForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = VehicleForm()
    return render(request,'index.html',{'form':form})
def show(request):
    vehicles = Vehicle.objects.all()
    return render(request,"show.html", {'vehicles':vehicles})
def edit(request, id):
    vehicle = Vehicle.objects.get(id=id)
    return render(request,'edit.html', {'vehicle':vehicle})
def update(request, id):
    vehicle = Vehicle.objects.get(id=id)
    form = VehicleForm(request.POST, instance = vehicle)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'vehicle': vehicle})
def destroy(request, id):
    vehicle = Vehicle.objects.get(id=id)
    vehicle.delete()
    return redirect("/show")

vehicle/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
</head>
<body>
<form method="POST" class="post-form" action="/update/{{ vehicle.id}}">
    {% csrf_token %}
    <div class="container">
        <br>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <h3>Update Details</h3>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Vehicle Id:</label>
            <div class="col-sm-4">
                <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ vehicle.eid }}"/>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Vehicle Type:</label>
            <div class="col-sm-4">
                <input type="text" name="etypeVehicle" id="id_etypeVehicle" required maxlength="100" value="{{ vehicle.etypeVehicle }}"/>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Vehicle Model:</label>
            <div class="col-sm-4">
                <input type="email" name="emodel" id="id_emodel" required maxlength="254"
                       value="{{ vehicle.emodel }}"/>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Vehicle Brand:</label>
            <div class="col-sm-4">
                <input type="text" name="ebrand" id="id_ebrand" required maxlength="100"
                       value="{{ vehicle.ebrand }}"/>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Vehicle Plate:</label>
            <div class="col-sm-4">
                <input type="text" name="eplate" id="id_eplate" required maxlength="100"
                       value="{{ vehicle.eplate }}"/>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Vehicle Mileage:</label>
            <div class="col-sm-4">
                <input type="text" name="emileage" id="id_emileage" required maxlength="100"
                       value="{{ vehicle.emileage }}"/>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </div>
    </div>
</form>
</body>
</html>

vehicle/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
</head>
<body>
<form method="POST" class="post-form" action="/emp">
    {% csrf_token %}
    <div class="container">
        <br>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <h3>Enter Details</h3>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Vehicle Id:</label>
            <div class="col-sm-4">
                {{ form.eid }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Vehicle Type:</label>
            <div class="col-sm-4">
                {{ form.etypeVehicle }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Vehicle Model:</label>
            <div class="col-sm-4">
                {{ form.emodel }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Vehicle Brand:</label>
            <div class="col-sm-4">
                {{ form.ebrand }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Vehicle Plate:</label>
            <div class="col-sm-4">
                {{ form.eplate }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Vehicle Mileage:</label>
            <div class="col-sm-4">
                {{ form.emileage }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>
</form>
</body>
</html>

vehicle/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vehicles</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Vehicle ID</th>
        <th>Vehicle Type</th>
        <th>Vehicle Model</th>
        <th>Vehicle Brand</th>
        <th>Vehicle Plate</th>
        <th>Vehicle Mileage</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for vehicle in vehicles %}
    <tr>
        <td>{{ vehicle.eid }}</td>
        <td>{{ vehicle.etypeVehicle }}</td>
        <td>{{ vehicle.emodel }}</td>
        <td>{{ vehicle.ebrand }}</td>
        <td>{{ vehicle.eplate }}</td>
        <td>{{ vehicle.emileage }}</td>
        <td>
            <a href="/edit/{{ vehicle.id }}"><span class="glyphicon glyphicon-pencil">Edit</span></a>
            <a href="/delete/{{ vehicle.id }}">Delete</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/emp" class="btn btn-primary">Add New Vehicle</a></center>
</body>
</html>